# Generated by Django 4.2.3 on 2023-11-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_name',
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.ManyToManyField(to='app.project'),
        ),
    ]
