# Generated by Django 4.2.3 on 2023-10-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'medium'), ('High', 'High')], max_length=50)),
                ('status', models.CharField(choices=[('To do', 'To do'), ('Progress', 'Progress'), ('Done', 'Done')], max_length=50)),
            ],
        ),
    ]
