# Generated by Django 4.2.3 on 2023-11-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('Progress', 'Progress'), ('Done', 'Done')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
